### ISSUE TITLE
Fluid Extractor from Embers Rekindled is not available

### ISSUE THREAD

**Issue by OMG-WHY-NO** [tyon2006/MMO---Here-We-Go-#10]
Fluid Extractor from Embers Rekindled is not available

When researching how to use this mod, the fluid extractor is used to pull fluid from a machine and send it through fluid pipe to a vessel or reservoir.  This item is not available, so i am unable to use this feature of the mod (which is necessary for power production and automation)

**Comment by OMG-WHY-NO** [comment]
correction, this item is incorrectly called the pollutant pump

**Comment by tyon2006** [comment]
corrected in latest version
