### ISSUE TITLE
Create Gungerstank Junkheap Biome

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#111]
Junkheap or Landfill Biome
Use BiomeTweaker to copy a hilly barren biome from BoP.
Make topsoil wasteland dried dirt.
Make water foul-colored.
Add patches of Garbage from Rats, and appropriate decorators.
This will be a T4 Neutral biome.
Add this biome to all T4 metal spawns.

**Comment by tyon2006** [comment]
As much as it pains me, I think we should let this one alone. Gungerstank it too low priority versus the grand scheme of things. Let's keep it to an instance for now.
