### ISSUE TITLE
Finalize fillers for gem dikes in COG

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#15]
- [x] Select palette of applicable liquids
- [x] Apply variation to gems by group; gems include all BoP variants and TC amber
- [x] Ensure all biomes have a representative gem

**Comment by tyon2006** [comment]
peridot: quicksand
sapphire: poison
tanzanite: crystalized obsidian
biome essence: liquid experience
ender biotite: tar
ender amethyst: stygian acid
peridot ore: ammonia
peridot: sulfuric acid
topaz: polluted water
malachite: hot spring water
ruby ore: alchemical slurry

![image](https://user-images.githubusercontent.com/26413035/95685435-e138f000-0bc5-11eb-9c3e-be91ec7bd46d.png)
