### ISSUE TITLE
Respawn health

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#193]
Starting with 2.5 hearts leaves you in one shot range for a lot of even tier 1 biome mobs(within the damage range of a vanilla skeleton). This allows the potential for a cascade of deaths as a mob immediately kills you on re-spawn over and over. Maybe consider going to 5 hearts or a temporary invulnerability buff to give you a moment to run far enough to get away or kite the mob away from your respawn.

**Comment by tyon2006** [comment]
This was originally intended to stop people from abusing death (IE, killing yourself instead of eating). I'm open to suggestions on how this should act.
