### ISSUE TITLE
Tomb many graves spam lists into inventory

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#194]
Tomb many graves forces its death inventory list into the first slot of the toolbar. Not only is this annoying replacing what is probably your most used or needed quickly tool, but it can force an item out of your toolbar allowing it to drop on death.

**Comment by tyon2006** [comment]
Cannot confirm this is still happening. 

On another note, I would like to be able to craft this paper into something. Ideas?

**Comment by tyon2006** [comment]
Let's make 3 of them craft into a grave scroll!
