### ISSUE TITLE
Buckets....

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#197]
Buckets appear to be only craft-able with iron, which is now explicitly not in tier 1 biomes. Buckets are a very basic vanilla tool and probably should have recipes added for low tier metals (like tin and copper.) Maybe consider doing the same for shears too.

**Comment by yashairi** [comment]
I am told iron will spawn in tier 1 biomes and the start quest needs correcting. Would still like to see buckets craftable from alternate metals.

**Comment by tyon2006** [comment]
How about making a bucket and shears recipe created by *any* ingots?
