### ISSUE TITLE
Hwaila not showing pickaxe power

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#198]
I distinctly remember Hwaila (or maybe from Waila) showing the pickax power needed to collect a block and if the one your holding qualifies. With the variety of pickax materials and blocks in mod-packs this was one of the most useful features from the mod.

**Comment by tyon2006** [comment]
I think you're talking about this mod:
https://www.curseforge.com/minecraft/mc-mods/waila-harvestability

@Caervec what do you think about adding this mod?

**Comment by Caervec** [comment]
I concur with Yash about this; the material variety is very broad in a pack like this, and can be hard to track without mechanical aids.
