### ISSUE TITLE
furnace not stacking output

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#2]
Furnace not stacking output, makes a single item and stops until removed. Replicate with stone and charcoal.

**Comment by yashairi** [comment]
replicate with potato. Iron ore will stack.

**Comment by tyon2006** [comment]
We figured this one out. Its an interaction between fastfurnace and customnpcs. Owner of Fastfurnace confirmed in discord. We're removing fastfurnace in the next release (to our dismay)
