### ISSUE TITLE
disable apotheosis cane

### ISSUE THREAD

**Issue by tyon2006** [tyon2006/MMO---Here-We-Go-#214]

**Comment by yashairi** [comment]
Apotheosis Sugar cane is interacting poorly with Inspirations sugar cane, allowing seeds to be duplicated while forcefully replacing inspirations sugar can with apotheosis' sugar cane.  The seeds are not used in any recipes, but are Thaumcraft aspected by the stack and can be used in the Composter. Between the two, Inspirations sugar cane is more like other crops and would be preferable to keep if possible.
