### ISSUE TITLE
Bronze armor exists but lacks recipes

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#220]
Bronze armor exists but lacks recipes

**Comment by tyon2006** [comment]
@Caervec, this is a leftover of commodities. Do we want this to be a thing? Do we want to CT basic armor sets for all industrial ore types?

**Comment by tyon2006** [comment]
Need to RH varied commodities extra items for now

**Comment by tyon2006** [comment]
have hidden armor for now, will hide more later
