### ISSUE TITLE
Tier 1 blueprint takes tier 5 metal to make

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#224]
Engineers blueprint for iron and steel components takes aluminum.

**Comment by yashairi** [comment]
Also Toolbox is tier 1 and requires aluminum.

**Comment by yashairi** [comment]
Vacuum tubes take nickel.

**Comment by tyon2006** [comment]
swapped aluminum out for tin
replaced aluminum with industrial ingot
replaced nickel with copper plate
