### ISSUE TITLE
Pigs Are FAST!

### ISSUE THREAD

**Issue by BadMuppet1** [tyon2006/MMO---Here-We-Go-#232]
In my experience handling hogs, which are a (hostile) mob, the hogs move insanely fast even when they do not have any additional effects on them. Fending them off is very difficult and will likely result in the death of a player attempting to defeat them. (This is before version 0.1.9.)

**Comment by tyon2006** [comment]
There was an issue with applying speed to mobs in 0.1.8.5. We've since fixed the configuration, but any mobs that were created under the old logic will continue to behave this way until their death.
