### ISSUE TITLE
Pharos Beacon has bugged inventory.

### ISSUE THREAD

**Issue by BadMuppet1** [tyon2006/MMO---Here-We-Go-#233]
The Pharos Beacon from Cyclic (as was tested in single player) takes any of the first 8 potions in the slots and sends them over to an invisible, uninteractable inventory space or to the first visible slot. Putting similar potions into the inventory causes such potions to stack in the first visible slot. (This was found in version 0.1.8)

**Comment by tyon2006** [comment]
Can you provide any video or screenshots of this? It sounds tricky and odds are we'll have to send it over to the Cyclic issues page. It could also be inventory tweaks doing something goofy, but that's much less likely.

**Comment by tyon2006** [comment]
Oh, I see what this is... okay. **This is expected behavior**. When you drop the potion into the slot, think of it like a right to left queue. When a potion goes in, it gets consumed and starts creating the potion aura. potions can stack up to 16 in this queue and you can order them.
