### ISSUE TITLE
Warp Stone Has No Cooldown (v. 0.1.9)

### ISSUE THREAD

**Issue by BadMuppet1** [tyon2006/MMO---Here-We-Go-#234]
I have interacted with the warp stone and it has no cooldown. I do not know if this is an intended effect or not. (Edit) The cooldown is working again.

**Comment by yashairi** [comment]
Caervec was abusing the server at the time, it probably got lagged out.

**Comment by tyon2006** [comment]
Yep! It does have a configured cooldown and testing under normal circumstances it works as expected. Dunno what Caer was doing, but it's likely not worth investigating at this time.
