### ISSUE TITLE
Feral wolf in tier 2 biome

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#235]
over 5k hp and moved so fast it might as well have teleported

**Comment by tyon2006** [comment]
This is likely a result of an event firing multiple times under the previous spawning logic. Updating the config files will not fix entities that existed before the config change was made (also the multi fire event problem is a systemic forge issue that we cannot address, so I doubly cannot actually do anything about that damn wolf).
