### ISSUE TITLE
(rustic)advanced alchemic condenser and retort need oredic change

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#236]
The advanced alchemic condenser and advanced alchemic retort take only vanilla nether brick to make, should be oredict to any nether brick.

**Comment by yashairi** [comment]
I am running into this issue a few times now, might be easier to make a recipe for anynetherrack into vanilla netherrack.

**Comment by yashairi** [comment]
I found one workaround, chisel can convert between the modded types and vanilla.

**Comment by tyon2006** [comment]
We cannot broadcast this as wide as an oredict change - there seem to be an equal number of recipes that call for the nether bricks by their item type and by their oredict. They're all actually dicitified already, so this is a by-recipe change. We've fixed the condenser parts for now.
