### ISSUE TITLE
nitrate dust

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#240]
After doing some wiki research for a new source of nitrate dust, I would recommend a drying basin recipe of beetroot soup to nitrate dust.

**Comment by tyon2006** [comment]
I assume you need this for gunpowder. Let's also make gunpowder take a little less of this.

**Comment by tyon2006** [comment]
added beetroot soup to nitrate recipe for rustic drying basin. cheers!
