### ISSUE TITLE
"tinker" villager has no trades

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#242]
There are several "tinker" villagers in the village but none of them have any trades of offer.

**Comment by tyon2006** [comment]
Not sure how those snuck in. We didn't make those. Funny how it matches the example in the tutorial but there are no instances of "tinkerer" anywhere in our repo lol. 


For now, I'd say kill the villagers and see if more respawn. It's possible something got through in an older version of the repo as we were playing with the mod, but it's probably a fluke.

If it comes back, let's re-open the case and I guess we'll make up a villager called "Tinkerer" and give him a loot table lol.
