### ISSUE TITLE
Tier 5 mob spawns incorrect

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#243]
Plague rats still spawn.
Quagmire has an issue with that, they also don't despawn, nor do sludge lords.
So Sluge Lords should probably be treated like either Rarespawns or the mini-bosses they are and not be spawned. They soak up all the mob spawn limit after a certain point.
I bandaided it by butcher bombing the quag in an 80 block radius

**Comment by tyon2006** [comment]
removed from spawning until we can figure out what to do with them. Maybe multi-block spawner as if they're a boss?
