### ISSUE TITLE
Mystical gears not working

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#246]
Mystical gears are not usable in the gearbox despite their text.

**Comment by tyon2006** [comment]
i tested 10 or so gears, they all appeared to work. need to make sure the iron anxle is pointing into the receiving hole of the gear box for it to work, it wont crank on every gear. in my case the gearbox hole was in the top
![image](https://user-images.githubusercontent.com/26413035/164121671-9a673569-ad31-4d56-8a5a-042bca12e00f.png)
