### ISSUE TITLE
sophisticated wolves and wolf armor and storage are not compatable atm.

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#248]
From wolf armor and storage's curseforge:

"Sophisticated Wolves by NightKosh
Currently functionality is broken due to an outdated API on the Sophisticated Wolves end."

Basically sophisticated wolves is not working in any real way right now on the server, and has not updated in two years.
The conflict also prevents you from breeding wolves.

**Comment by tyon2006** [comment]
I was already aware of this issue and my testing did not reproduce it. Did you experience this issue yourself?

**Comment by tyon2006** [comment]
confirmed latest updates to soph wolves does not fix. reclosing
