### ISSUE TITLE
Configure Worley's Caves

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#30]
Default may actually be perfect, but play around with it.

**Comment by tyon2006** [comment]
![image](https://user-images.githubusercontent.com/26413035/95485258-7ab29880-095f-11eb-8c70-5f434eabbc5f.png)

    # Controls size of caves. Smaller values = larger caves. Between -1.0 and 1.0
    # Default: -0.18
    D:noiseCutoffValue=-0.5

    # Squishes caves on the Y axis. Lower values = taller caves and more steep drops
    # Default: 2.0
    D:verticalCompressionMultiplier=1.8

    # Controls how much to warp caves. Lower values = straighter caves
    # Default: 8.0
    D:warpAmplifier=4.0

**Comment by tyon2006** [comment]
![image](https://user-images.githubusercontent.com/26413035/95497625-a12cff80-0970-11eb-8564-074cfec68fff.png)

    # Controls size of caves. Smaller values = larger caves. Between -1.0 and 1.0
    # Default: -0.18
    D:noiseCutoffValue=-0.18

    # Controls size of caves at the surface. Smaller values = more caves break through the surface. Between -1.0 and 1.0
    # Default: -0.081 (45% of noiseCutoffValue)
    D:surfaceCutoffValue=-0.081

    # Squishes caves on the Y axis. Lower values = taller caves and more steep drops
    # Default: 2.0
    D:verticalCompressionMultiplier=1.5

    # Controls how much to warp caves. Lower values = straighter caves
    # Default: 8.0
    D:warpAmplifier=6.0
