### ISSUE TITLE
come up with a way for people to get to a level 1 biome, early. BQ maybe?

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#40]
Add a quest for singleplayer that will run a /biomesop tpbiome # command at player discretion, allow them to choose which biome if possible.

**Comment by tyon2006** [comment]
Not feasible to do randomly. Can add quests that allow for the direct travel of a biome in BQ. Moving to quests update.

**Comment by tyon2006** [comment]
We can't implement this. We took a whack at it by suggesting to BiomeTweaker which biomes can be used as spawn biomes, but minecraft only searches for those for a moment before it dumps you out. The BOP command to TP you to a biome also has a minimum distance it will search and also cannot be aliased to a player via BQ. Juice aint worth the squeeze
