### ISSUE TITLE
Set Nyx fallen stars to fill in several recipes in place of glowstone for early-game requirements such as ThaumCraft nitor

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#45]
Pay particular attention to TC, as the discipline calls for several nether components very early that cannot be provided and must have substitutions available

- [x] Dictify Nyx stars as glowstone
- [x] Verify impacted recipes

**Comment by tyon2006** [comment]
let's use unidict to dictify these items as replacements for glowstone
