### ISSUE TITLE
Kicked from server when using nametag on tamed wolf

### ISSUE THREAD

**Issue by OMG-WHY-NO** [tyon2006/MMO---Here-We-Go-#5]
When naming a Sophisticated Wolf using a Name Tag from the same modpack you get kicked from the server
![Error](https://user-images.githubusercontent.com/64548467/80622927-7cbf1580-8a17-11ea-8796-1162cb262768.png)

**Comment by tyon2006** [comment]
unable to reproduce, is no longer occurring.
