### ISSUE TITLE
Embers Rekindled Mechanical Core needed in Basics level of Bawls skill tree

### ISSUE THREAD

**Issue by OMG-WHY-NO** [tyon2006/MMO---Here-We-Go-#9]
Embers Rekindled Mechanical Core needed in Basics level of Bawls skill tree, otherwise the ember bore cannot be crafted or used

**Comment by OMG-WHY-NO** [comment]
after dicsussing with Tyon, this item will be replaced with the Machine Accessor in the recipes for the Basics skill level items

**Comment by tyon2006** [comment]
corrected in latest version
