### ISSUE TITLE
Correct "Proprietary" Item Names

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#95]
Some items names should be made more generic to reflect their broader nature in the pack, such as Nether Quartz which may now be found outside of the Nether.
Including but not limited to:
- [x] Nether Quartz
- [ ] Ender Amethyst
- [ ] Ender Biotite

**Comment by tyon2006** [comment]
Suggest fixing these items and closing this release. Scope too broad on issue. Suggest making individual issues for all future suggestions.

**Comment by tyon2006** [comment]
All the items on this list are actually already done, now that I double check on it. Let's create cards for ones we find in the future and close them, then.
