### ISSUE TITLE
Correct Broken Names

### ISSUE THREAD

**Issue by Caervec** [tyon2006/MMO---Here-We-Go-#96]
Correct names that appear to reference incorrect or missing lang entries. 
Also correct names to match pack vision and character.
- [x] Embers pump pipe
- [x] Bauxite ore to Aluminum ore?
- [x] Aluminium products to "Aluminum" (US Localization)
- [x] Radiant Crystals (there are two of them, rename one for clarity)

**Comment by tyon2006** [comment]
first 2 were done in other releases, localization is already done in oredict (which is nice) but there are 63 items and im not sure that can be done completely, the fluids and materials will stick around in JEI, as we can only rename the finished products themselves, not the fluid names... so the juice may not be worth the squeeze here. 

renamed radiant crystals and other related blocks from EB to "dazzling"
